### ISSUE TITLE
Filtering path operations by tags

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-network#49] opened 2021-01-20 07:47 UTC
Need to implement filtration path operations by tags.

For example I have this path:

```yaml
  '/api/request':
    get:
      operationId: api_request_get
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - api
    delete:
      operationId: api_request_delete
      description: ''
      responses:
        '204':
          description: ''
      tags:
        - internal
        - api
```

And sometimes I need generate api without operations with tag `internal`. In this example, I don't need `delete` method in the api class, so I want to filter it by the `internal` tag

**Comment by Alex009** [comment] 2021-01-20 07:53
duplicate of #46

**Closed** 2021-01-20 07:54 UTC
Labels: duplicate
